name = "buzzu-signaling"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "RoomDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]