name = "buzzu-signaling"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cargo install worker-build && worker-build --release"

[durable_objects]
bindings = [{ name = "ROOMS", class_name = "RoomDurableObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]